import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { NavLink } from 'react-router-dom';
const items = [
    { to: '/chat', icon: '💬', label: 'Chat Assistant', desc: 'Ask anything' },
    { to: '/search', icon: '🔍', label: 'Search Trains', desc: 'Find trains' },
    { to: '/bookings', icon: '🎫', label: 'My Bookings', desc: 'View & manage' },
];
const Sidebar = () => (_jsxs("aside", { className: "hidden md:flex flex-col w-64 shrink-0 border-r border-white/10 p-4 gap-2", style: { background: 'rgba(15,23,42,0.9)', backdropFilter: 'blur(20px)' }, children: [_jsxs("div", { className: "mb-6 px-2", children: [_jsxs("div", { className: "flex items-center gap-3 mb-1", children: [_jsx("span", { className: "text-2xl", children: "\uD83D\uDE86" }), _jsxs("div", { children: [_jsx("p", { className: "font-bold text-white text-sm leading-tight", children: "RailAI" }), _jsx("p", { className: "text-xs text-primary-400", children: "Indian Railways Assistant" })] })] }), _jsx("div", { className: "mt-3 h-px bg-gradient-to-r from-primary-500/50 via-purple-500/30 to-transparent" })] }), _jsx("nav", { className: "flex flex-col gap-1", children: items.map(({ to, icon, label, desc }) => (_jsx(NavLink, { to: to, className: ({ isActive }) => `flex items-center gap-3 px-3 py-3 rounded-xl transition-all duration-200 group ${isActive
                    ? 'bg-primary-500/20 border border-primary-500/30 text-white'
                    : 'text-slate-400 hover:bg-white/5 hover:text-white border border-transparent'}`, children: ({ isActive }) => (_jsxs(_Fragment, { children: [_jsx("span", { className: `text-lg transition-transform duration-200 ${isActive ? '' : 'group-hover:scale-110'}`, children: icon }), _jsxs("div", { className: "flex flex-col min-w-0", children: [_jsx("span", { className: `text-sm font-medium leading-tight ${isActive ? 'text-primary-300' : ''}`, children: label }), _jsx("span", { className: "text-xs text-slate-500 truncate", children: desc })] }), isActive && (_jsx("div", { className: "ml-auto w-1.5 h-1.5 rounded-full bg-primary-400 shrink-0" }))] })) }, to))) }), _jsx("div", { className: "mt-auto px-2 pt-4 border-t border-white/5", children: _jsxs("p", { className: "text-xs text-slate-500 leading-relaxed", children: ["\uD83D\uDCA1 Try: ", _jsx("em", { className: "text-slate-400", children: "\"Find trains from Bangalore to Mumbai\"" })] }) })] }));
export default Sidebar;
