import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Routes, Route, Navigate } from 'react-router-dom';
import Login from './pages/Login';
import Register from './pages/Register';
import ChatAssistant from './pages/ChatAssistant';
import TrainSearch from './pages/TrainSearch';
import BookingDashboard from './pages/BookingDashboard';
import Sidebar from './components/Sidebar';
import Navbar from './components/Navbar';
const App = () => (_jsxs("div", { className: "flex h-screen overflow-hidden bg-dark", children: [_jsx(Sidebar, {}), _jsxs("div", { className: "flex flex-col flex-1 overflow-hidden", children: [_jsx(Navbar, {}), _jsx("main", { className: "flex-1 overflow-auto p-4 md:p-6 custom-scroll", children: _jsxs(Routes, { children: [_jsx(Route, { path: "/login", element: _jsx(Login, {}) }), _jsx(Route, { path: "/register", element: _jsx(Register, {}) }), _jsx(Route, { path: "/chat", element: _jsx(ChatAssistant, {}) }), _jsx(Route, { path: "/search", element: _jsx(TrainSearch, {}) }), _jsx(Route, { path: "/bookings", element: _jsx(BookingDashboard, {}) }), _jsx(Route, { path: "/", element: _jsx(Navigate, { to: "/chat", replace: true }) })] }) })] })] }));
export default App;
